name: Sequential Jobs

on:
  push:
    branches:
      - sequential_jobs

Jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: action/checkout@v4
      - name: Install NodeJs
        uses: action/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: action/checkout@v4
      - name: Install NodeJs
        uses: action/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
