name: Output Information

on:
  workflow_dispatch:
    branches:
      - context_expression

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJSON(github) }}"
